#!/bin/bash
#set -e
failed=0
for i in '1'; do \
  if ! cmp -s <(terraform-docs markdown table --sort-inputs-by-required --with-aggregate-type-defaults "./") "./README.md"; then \
    echo "Updating readme" && terraform-docs markdown table --sort-inputs-by-required --with-aggregate-type-defaults "./" > ./README.md && git add ./README.md && break || failed=1; \
  fi
done

if [ $failed -eq 1 ]; then \
  echo "Failed to run: terraform-docs markdown table --sort-inputs-by-required --with-aggregate-type-defaults \"./\"" \
  exit 1 \
fi
